name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: alen-devops-gcp
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install kubectl and GKE auth plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl google-cloud-cli-gke-gcloud-auth-plugin

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/alen-devops-gcp/webapp:${{ github.sha }} .
        docker push gcr.io/alen-devops-gcp/webapp:${{ github.sha }}
